encoding: utf-8
port: 5678
host: 0.0.0.0

title: Fooleap's Blog
keywords: [fooleap, 前端, Linux, 潮汕]
description: 'A foolish man could not always lose!'

exclude: [node_modules, src, webpack.config.js, package.json]
gems: [jekyll-paginate]

permalink: /:title.html
highlighter: rouge
markdown: kramdown
kramdown: 
  auto_ids:       true
  auto_id_prefix: 'id-'
  toc_levels:     '2,3'
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
paginate: 10
repository: fooleap/fooleap.github.io

nickname: fooleap
home: http://blog.fooleap.org
api: http://api.fooleap.org
IMG_PATH: http://source.fooleap.org
tongji: 'fa7ec982118ebd236663169678264582'
analytics: 'UA-16717905-7'
