encoding: utf-8
port: 5678
host: 0.0.0.0

title: Fooleap's Blog
keywords: [fooleap, 前端, 跑步, 潮汕]
description: 'A foolish man could not always lose!'

exclude: [webpack.config.js, package.json, Gemfile, Gemfile.lock, src, node_modules]
gems: [jekyll-paginate, jemoji]

permalink: /:title.html
highlighter: rouge
markdown: kramdown
kramdown: 
  auto_ids:       true
  auto_id_prefix: 'id-'
  toc_levels:     '2,3'
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
emoji:
    src: 'http://api.fooleap.org'
paginate: 10
repository: fooleap/fooleap.github.io

nickname: fooleap
home: http://blog.fooleap.org
api: http://api.fooleap.org
IMG_PATH: http://source.fooleap.org
tongji: 'fa7ec982118ebd236663169678264582'
analytics: 'UA-16717905-7'
