encoding: utf-8
title: Fooleap's Blog
email: fooleap@gmail.com
description: "A foolish man could not always lose!"
baseurl: ""
url: "http://blog.fooleap.org"
twitter_username: fooleap
github_username: fooleap
weibo_username: fooleap
timezone: Asia/Shanghai
markdown: kramdown
permalink: /:title.html 
highlighter: pygments
paginate: 10
IMG_PATH: http://fooleap.qiniudn.com
kramdown: 
  toc_levels: "2,3" 
