encoding: utf-8
title: Fooleap's Blog
email: fooleap@gmail.com
keywords: [fooleap, 前端, Linux, 潮汕]
description: "A foolish man could not always lose!"
url: "http://blog.fooleap.org"
timezone: Asia/Shanghai
permalink: /:title.html 
highlighter: pygments
paginate: 10
IMG_PATH: http://7fv9cr.com1.z0.glb.clouddn.com
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
kramdown: 
  toc_levels: "2,3" 
defaults:
  -
    scope:
      path: "_posts"
      type: posts 
    values:
      is_post: true
twitter_username: fooleap
github_username: fooleap
weibo_username: fooleap
